meta:
  engine: 4.2.1
units:
  mx: U # 19.05mm for MX switch footprint, 18.00mm for keycaps, 14.00mm for plate holes
  $default_width: U - 1
  $default_height: U - 1
  pd: 2
  px: mx + pd
  py: mx + pd
points:
  key:
    tags:
    - key
    padding: 1mx
    spread: 1mx
  zones:
    matrix:
      anchor:
        shift: [80, -180] # Fix KiCad placement
      columns:
        c0:
          key:
            column_net: P2
            mirror.column_net: P21
        c1:
          key:
            column_net: P3
            mirror.column_net: P20
        c2:
          key:
            stagger: mx/2
            column_net: P4
            mirror.column_net: P19
        c3:
          key:
            stagger: mx/4
            column_net: P5
            mirror.column_net: P5
        c4:
          key:
            stagger: -mx/8
            column_net: P19
            mirror.column_net: P4
          rows.mods.skip: true
        c5:
          key:
            stagger: -mx/8
            column_net: P20
            mirror.column_net: P3
          rows.mods.skip: true
        c6:
          key:
            stagger: -mx/2
            column_net: P21
            mirror.column_net: P2
          rows.r3.skip: true
          rows.mods.skip: true
      rows:
        mods:
          row_net: P10
          mirror.row_net: P10
        r3:
          row_net: P9
          mirror.row_net: P9
        r2:
          row_net: P8
          mirror.row_net: P8
        r1:
          row_net: P7
          mirror.row_net: P7
        r0:
          row_net: P6
          mirror.row_net: P6
    thumbfan:
      anchor:
        - ref: matrix_c4_r3
          shift: [mx/2, -mx - 4.75]
      columns:
        t0:
          key:
            splay: -22
            shift: [0, 0]
            width: 1.5mx
            tags: [key, key_1_5uw]
            column_net: P20
            mirror.column_net: P3
        t1:
          key:
            splay: 0
            shift: [0, mx/4]
            spread: 1.255mx
            height: 1.5mx
            tags: [key, key_1_5u]
            column_net: P21
            mirror.column_net: P2
      rows:
        r0:
          row_net: P10
          mirror.row_net: P10
  mirror: &mirror
    ref: matrix_c6_r0
    distance: 2.5mx
outlines:
  _thumbfan_enclosed_left:
    - what: polygon
      operation: stack
      fillet: 0
      points:
        - ref: matrix_c3_mods
          shift: [mx/2 - 0.5, -mx/2 - 0.5]
        - ref: matrix_c3_mods
          shift: [mx/2, mx/2]
        - ref: matrix_c3_mods
          shift: [2.5mx + 0.5, mx/2]
        - ref: matrix_c5_r3
          shift: [mx/2 + 0.5, -mx/2 + 1.25]
        - ref: thumbfan_t1_r0
          shift: [mx/2 + 0.5, 1.5mx/2 + 0.5] # top-right t1
        - ref: thumbfan_t1_r0
          shift: [mx/2 + 0.5, -1.5mx/2 - 0.5] # bottom-right t1
  _thumbfan_enclosed_right:
    - what: polygon
      operation: stack
      fillet: 0
      points:
        - ref: mirror_matrix_c3_mods
          shift: [mx/2 - 0.5, -mx/2 - 0.5]
        - ref: mirror_matrix_c3_mods
          shift: [mx/2, mx/2]
        - ref: mirror_matrix_c3_mods
          shift: [2.5mx + 0.5, mx/2]
        - ref: mirror_matrix_c5_r3
          shift: [mx/2 + 0.5, -mx/2 + 1.25]
        - ref: mirror_thumbfan_t1_r0
          shift: [mx/2 + 0.5, 1.5mx/2 + 0.5] # top-left t1
        - ref: mirror_thumbfan_t1_r0
          shift: [mx/2 + 0.5, -1.5mx/2 - 0.5] # bottom-left t1
  _keys_enclosed:
    - what: rectangle
      where: /(?:^matrix_|^mirror_matrix_).*/
      size: mx + 1
      fillet: 0
    - what: outline
      name: _thumbfan_enclosed_left
      operation: add
    - what: outline
      name: _thumbfan_enclosed_right
      operation: add
      expand: 0.25
  _key_cutouts:
    - what: rectangle
      where: true
      size: [14, 14] # plate hole cutouts are 14.00mm x 14.00mm
  _key_cutouts_left:
    - what: rectangle
      where: /(?:^matrix_|^thumbfan_).*/
      size: [14, 14]
  keycaps: # Keycaps are 18.00mm x 18.00mm
    - what: rectangle
      where: true
      size: mx - 1
      fillet: 1
    - what: rectangle
      where: [key_1_5uw]
      size: [1.5mx-1, mx-1]
      fillet: 1
    - what: rectangle
      where: [key_1_5u]
      size: [mx-1, 1.5mx-1]
      fillet: 1
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_c0_r0 # top-left board
          shift: [-px/2, py/2]
        - ref: matrix_c3_r0
          shift: [-3px/2, py/2]
        - ref: matrix_c3_r0
          shift: [1.85px - pd, py/2]
        - ref: matrix_c6_r0
          shift: [px/2, py/2] # top-right board
        - ref: matrix_c6_r0
          shift: [px/2, -3py - 1] # top-right t1
        # - ref: thumbfan_t1_r0
        #   shift: [px/2, 1.5py/2] # top-right t1 (use for slope correction)
        - ref: thumbfan_t1_r0
          shift: [px/2, -1.45py/2] # bottom-right t1
        - ref: thumbfan_t0_r0
          shift: [-1.5px/2, -py/2] # bottom-left t0
        - ref: matrix_c1_mods
          shift: [px/2 - 1, -py/2]
        - ref: matrix_c0_mods
          shift: [-px/2, -py/2]
        - ref: matrix_c0_r3
          shift: [-px/2, -py/2]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_c0_r0 # top-right board
          shift: [-px/2, py/2]
        - ref: mirror_matrix_c3_r0
          shift: [-3px/2, py/2]
        - ref: mirror_matrix_c3_r0
          shift: [1.85px - pd, py/2]
        - ref: mirror_matrix_c6_r0
          shift: [px/2, py/2] # top-left board
        - ref: mirror_matrix_c6_r0
          shift: [px/2, -3py - 1] # top-left t1
        # - ref: mirror_thumbfan_t1_r0
        #   shift: [px/2, 1.5py/2] # top-left t1 (use for slope correction)
        - ref: mirror_thumbfan_t1_r0
          shift: [px/2, -1.45py/2] # bottom-left t1
        - ref: mirror_thumbfan_t0_r0
          shift: [-1.5px/2, -py/2] # bottom-right t0
        - ref: mirror_matrix_c1_mods
          shift: [px/2 - 1, -py/2]
        - ref: mirror_matrix_c0_mods
          shift: [-px/2, -py/2]
        - ref: mirror_matrix_c0_r3
          shift: [-px/2, -py/2]
  board_full:
    - what: outline
      name: board_left
      operation: stack
    - what: outline
      name: board_right
      operation: stack
  preview:
    - what: outline
      name: board_left
      operation: stack
    - what: outline
      name: board_right
      operation: stack
    - what: outline
      name: keycaps
      operation: stack
  plate:
    - what: outline
      name: board_left
      operation: stack
    - what: outline
      name: board_right
      operation: stack
    - what: outline
      name: _key_cutouts
      operation: stack
  plate_left:
    - what: outline
      name: board_left
      operation: stack
    - what: outline
      name: _key_cutouts_left
      operation: stack
  preview_w_case:
    - what: outline
      name: board_left
      operation: stack
    - what: outline
      name: board_right
      operation: stack
      expand: 8
    - what: outline
      name: _keys_enclosed
      operation: subtract
      fillet: 1
    - what: outline
      name: keycaps
      operation: stack
  bottom_case:
    - what: outline
      name: board_left
      expand: 9
pcbs:
  keeb_left:
    template: kicad8
    outlines:
      board_left:
        outline: board_left
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: /(?:^matrix_)(?!(?:c3_r[0-1])).*/
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_hotswap_mcu:
        what: ceoloide/switch_mx
        where: /(?:^matrix_)(?:c3_r[0-1]).*/
        adjust:
          rotate: -90
        params:
          # keycap_width: 14 # for helping align mcu through holes
          # keycap_height: 14
          include_keycap: true
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_t0:
        what: ceoloide/switch_mx
        where: /(?:^thumbfan_)(?:t0_).*/
        params:
          include_keycap: true
          keycap_width: 27.575 # 19.05mm * 1.5 - 1
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_t1:
        what: ceoloide/switch_mx
        where: /(?:^thumbfan_)(?:t1_).*/
        params:
          include_keycap: true
          keycap_height: 27.575 # 19.05mm * 1.5 - 1
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_left:
        what: ceoloide/diode_tht_sod123
        where: /(?:^matrix_|^thumbfan_)(?!(?:c3_r[0-1])).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [mx/2 - 4, -5]
          rotate: 90
      diode_mcu_left:
        what: ceoloide/diode_tht_sod123
        where: /(?:^matrix_)(?:c3_r[0-1]).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3.6, -mx/2 + 4]
          rotate: 90
      battery_jst_left:
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_c1_r0
        adjust:
          shift: [-7.2, mx/2 + 3.2]
          rotate: 90
        params:
          side: B
      reset_switch_left:
        what: ceoloide/reset_switch_smd_side
        where: matrix_c4_r0 
        params:
          side: B
          from: GND
          to: RST
          reversible: false
        adjust:
          shift: [0, mx/2 + 1.50]
          rotate: 0
      power_switch_left:
        what: ceoloide/power_switch_smd_side
        where: matrix_c2_r0 
        params:
          side: B
          from: BAT_P
          to: RAW
          reversible: false
          invert_behavior: true
        adjust:
          shift: [0, mx - 5.5]
          rotate: 90
      mcu_left:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_c3_r0
          rotate: 0
          shift: [0.6, -6]
        params:
          side: B
          reverse_mount: true
  keeb_right:
    template: kicad8
    outlines:
      board_left:
        outline: board_right
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: /(?:^mirror_matrix_)(?!(?:c3_r[0-1])).*/
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_hotswap_mcu:
        what: ceoloide/switch_mx
        where: /(?:^mirror_matrix_)(?:c3_r[0-1]).*/
        adjust:
          rotate: -90
        params:
          # keycap_width: 14 # for helping align mcu through holes
          # keycap_height: 14
          include_keycap: true
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_t0:
        what: ceoloide/switch_mx
        where: /(?:^mirror_thumbfan_)(?:t0_).*/
        params:
          include_keycap: true
          keycap_width: 27.575 # 19.05mm * 1.5 - 1
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_t1:
        what: ceoloide/switch_mx
        where: /(?:^mirror_thumbfan_)(?:t1_).*/
        params:
          include_keycap: true
          keycap_height: 27.575 # 19.05mm * 1.5 - 1
          reversible: false
          hotswap: true
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_right:
        what: ceoloide/diode_tht_sod123
        where: /(?:^mirror_matrix_|^mirror_thumbfan_)(?!(?:c3_r[0-1])).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-mx/2 + 4, -5]
          rotate: -90
      diode_mcu_right:
        what: ceoloide/diode_tht_sod123
        where: /(?:^mirror_matrix_)(?:c3_r[0-1]).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3.6, -mx/2 + 4]
          rotate: -90
      battery_jst_right:
        what: ceoloide/battery_connector_jst_ph_2
        where: mirror_matrix_c1_r0
        adjust:
          shift: [-7.2, mx/2 + 3.2]
          rotate: 90
        params:
          side: B
      reset_switch_right:
        what: ceoloide/reset_switch_smd_side
        where: mirror_matrix_c4_r0 
        params:
          side: B
          from: GND
          to: RST
          reversible: false
        adjust:
          shift: [0, mx/2 + 1.50]
          rotate: 0
      power_switch_right:
        what: ceoloide/power_switch_smd_side
        where: mirror_matrix_c2_r0 
        params:
          side: B
          from: BAT_P
          to: RAW
          reversible: false
          invert_behavior: false
        adjust:
          shift: [0, mx - 5.5]
          rotate: -90
      mcu_right:
        what: ceoloide/mcu_nice_nano
        where:
          ref: mirror_matrix_c3_r0
          rotate: 0
          shift: [0.6, -6]
        params:
          side: B
          reverse_mount: true
cases:
  bot_case:
    - what: outline
      name: bottom_case
      extrude: 12
    - what: outline
      name: board_left
      extrude: 8.5
      shift: [0, 0, 3.5]
      operation: subtract
  key_plate:
    - what: outline
      name: plate
      extrude: 1.5  

